---
AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'bin/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/fixtures/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
