sudo: false
notifications:
  email: false

language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.0.0
      env: TEST='unit system'
    - rvm: 2.1.10
      env: TEST=default
    - rvm: 2.2.6
      env: TEST='unit system'
    - rvm: 2.3.3
      env: TEST='unit system'
    - rvm: 2.4.0
      env: TEST='unit system'

before_install: gem update --no-rdoc --no-ri bundler
install: bundle install --retry=3
script: bundle exec rake $TEST
