# setup environment
dist: trusty
sudo: false
language: ruby
cache: bundler

notifications:
  email: false

git:
  depth: 5

# setup tests
matrix:
  include:
    - rvm: 2.0.0
      env: TEST='unit system'
    - rvm: 2.1.10
      env: TEST='unit system'
    - rvm: 2.2.8
      env: TEST=default
    - rvm: 2.3.5
      env: TEST='unit system'
    - rvm: 2.4.2
      env: TEST='unit system'
    - rvm: 2.5.0-preview1
      env: TEST='unit system'
  allow_failures:
    - rvm: 2.5.0-preview1

# execute tests
before_install: gem update --no-document bundler
install:
  - bundle install --retry=3
  - bundle binstubs puppet
script: bundle exec rake $TEST
